sudo: required
dist: trusty
language: ruby
rvm:
  - "2.0.0"
  - "2.2.4"
  - "2.3.0"
env:
  - COVERAGE=true
script: "bundle exec rspec"

sudo: false

notifications:
  recipients:
    - DL-PP-Ruby-SDK@paypal.com
