test: &default
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  app_id: APP-80W284485P519543T
  http_timeout: 30
  mode: sandbox
  sandbox_email_address: Platform.sdk.seller@gmail.com
  logfile: spec/log/test.log
  ca_file: <%= File.expand_path("../cacert.pem", __FILE__) %>
  ipn_end_point: https://www.sandbox.paypal.com/cgi-bin/webscr

development:
  <<: *default

with_certificate:
  <<: *default
  username: platfo_1255170694_biz_api1.gmail.com
  password: 2DPPKUPKB7DQLXNR
  signature:
  cert_path: <%= File.expand_path("../cert_key.pem", __FILE__) %>
  app_id: APP-80W284485P519543T

with_oauth_token:
  <<: *default
  token: 3rMSi3kCmK1Q3.BKxkH29I53R0TRLrSuCO..l8AMOAFM6cQhPTTrfQ
  token_secret: RuE1j8RNRlSuL5T-PSSpVWLvOlI

with_proxy:
  <<: *default
  http_proxy: <%= ENV['http_proxy'] %>
