test: &default
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  app_id: APP-80W284485P519543T
  http_timeout: 30
  http_retry: 5
  http_trust: false
  mode: sandbox
  redirect_url: "https://www.sandbox.paypal.com/webscr&cmd="
  dev_central_url: "https://developer.paypal.com"

development:
  <<: *default

with_certificate:
  <<: *default
  username: platfo_1255170694_biz_api1.gmail.com
  password: 2DPPKUPKB7DQLXNR
  signature:
  cert_path: "spec/config/cert_key.pem"
  app_id: APP-80W284485P519543T

with_oauth_token:
  <<: *default
  token: ESTy2hio5WJQo1iixkH29I53RJxaS0Gvno1A6.YQXZgktxbY4I2Tdg
  token_secret: ZKPhUYuwJwYsfWdzorozWO2U9pI

with_proxy:
  <<: *default
  http_proxy: <%= ENV['http_proxy'] %>
